language: cpp
before_install:
    -   sudo add-apt-repository ppa:h-rayflood/llvm -y
    -   sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    -   sudo apt-get update -y
    -   sudo apt-get install cmake ragel lemon llvm-3.3
    -   if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    -   if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
compiler:
    -   gcc
    -   clang
script:
    -   mkdir build
    -   cd build
    -   cmake -DLLVM_CONFIG_NAME=llvm-config-3.3 ..
    -   make
    -   make test
