language: cpp
before_install:
    -   sudo apt-get install cmake llvm-dev ragel lemon cxxtest
compiler:
    -   gcc
    -   clang
script:
    -   mkdir build
    -   cd build
    -   cmake ..
    -   make
    -   make run_tests
