ECMA_DEFINE_LEXEME(End, 0)

ECMA_AUTO_LEXEME(Spaces)
ECMA_AUTO_LEXEME(Newline)

ECMA_LEXEME(If)
ECMA_LEXEME(Var)
ECMA_LEXEME(Else)
ECMA_LEXEME(Null)
ECMA_LEXEME(True)
ECMA_LEXEME(False)
ECMA_LEXEME(Return)
ECMA_LEXEME(Function)
ECMA_LEXEME(Undefined)

ECMA_LEXEME(Plus)
ECMA_LEXEME(Minus)
ECMA_LEXEME(Mul)
ECMA_LEXEME(Div)
ECMA_LEXEME(Mod)

ECMA_LEXEME(Assign)
ECMA_LEXEME(PlusAssign)
ECMA_LEXEME(MinusAssign)
ECMA_LEXEME(MulAssign)
ECMA_LEXEME(DivAssign)
ECMA_LEXEME(ModAssign)

ECMA_LEXEME(Greater)
ECMA_LEXEME(GreaterOrEqual)
ECMA_LEXEME(Lesser)
ECMA_LEXEME(LesserOrEqual)
ECMA_LEXEME(Equal)
ECMA_LEXEME(NotEqual)

ECMA_LEXEME(Not)
ECMA_LEXEME(Inv)
ECMA_LEXEME(Incrementation)
ECMA_LEXEME(Decrementation)

ECMA_LEXEME(LParen)
ECMA_LEXEME(RParen)
ECMA_LEXEME(LBracket)
ECMA_LEXEME(RBracket)
ECMA_LEXEME(LBrace)
ECMA_LEXEME(RBrace)

ECMA_LEXEME(QuestionMark)
ECMA_LEXEME(Dot)

ECMA_LEXEME(Semicolon)
ECMA_LEXEME(Colon)
ECMA_LEXEME(Comma)

ECMA_LEXEME(Identifier)

ECMA_LEXEME(Number)
ECMA_LEXEME(String)
