ECMA_TOKEN_DEFINE(END, 0)

ECMA_TOKEN_AUTO(UNKNOWN)
ECMA_TOKEN_AUTO(SPACES)
ECMA_TOKEN_AUTO(NEWLINE)
ECMA_TOKEN_AUTO(COMMENT)

ECMA_TOKEN(REGEXP)
ECMA_TOKEN(STRING)
ECMA_TOKEN(NUMBER)
ECMA_TOKEN(IDENT)

{{ types }}
