ECMA_DEFINE_LEXEME(End, 0)

ECMA_AUTO_LEXEME(Spaces)
ECMA_AUTO_LEXEME(Newline)

ECMA_LEXEME(Var)
ECMA_LEXEME(Null)
ECMA_LEXEME(Undefined)
ECMA_LEXEME(Return)

ECMA_LEXEME(Assign)
ECMA_LEXEME(Plus)
ECMA_LEXEME(Minus)
ECMA_LEXEME(Mul)
ECMA_LEXEME(Div)
ECMA_LEXEME(Mod)

ECMA_LEXEME(Not)
ECMA_LEXEME(Inv)

ECMA_LEXEME(LParen)
ECMA_LEXEME(RParen)
ECMA_LEXEME(LBracket)
ECMA_LEXEME(RBracket)
ECMA_LEXEME(LBrace)
ECMA_LEXEME(RBrace)

ECMA_LEXEME(Dot)

ECMA_LEXEME(Semicolon)
ECMA_LEXEME(Colon)
ECMA_LEXEME(Comma)

ECMA_LEXEME(Identifier)

ECMA_LEXEME(Number)
ECMA_LEXEME(String)
